[package]
name = "taprelay-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "taprelay"
path = "src/main.rs"

[dependencies]
taprelay-core.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow = "1.0.104"
serde_json = "1.0.151"
time = { version = "0.3.55", features = [
    "formatting",
    "local-offset",
    "macros",
] }
slint = { version = "=1.17.1", default-features = false, features = [
    "std",
    "backend-winit",
    "unstable-winit-030",
    "renderer-software",
    "compat-1-2",
    "accessibility",
] }
tracing-subscriber = { version = "0.3.23", features = ["json"] }
tracing-appender = "0.2.5"
tempfile = "3.27.0"

[build-dependencies]
slint-build = "=1.17.1"
serde_json = "1.0.151"
lucide-slint = "1.47.0"

[dev-dependencies]
i-slint-backend-testing = { version = "=1.17.1", features = [
    "renderer-software",
] }

[target.'cfg(windows)'.dependencies]
i-slint-core = "=1.17.1"
taprelay-windows = { path = "../taprelay-windows" }
